# This file is included from the main CMakeLists in the parent directory.

include(ExternalProject)

set(LIST_SEPARATOR "!")
string(REPLACE ";" "${LIST_SEPARATOR}" OSX_ARCHITECTURES_LISTSEP "${CMAKE_OSX_ARCHITECTURES}")
string(REPLACE ";" "," OSX_ARCHITECTURES_COMMA "${CMAKE_OSX_ARCHITECTURES}")



# Add libASPL
ExternalProject_Add(libASPL
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/lib/libASPL
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/lib/libASPL
  LIST_SEPARATOR ${LIST_SEPARATOR}
  CMAKE_ARGS
    -DCMAKE_CXX_COMPILER_LAUNCHER=${CMAKE_CXX_COMPILER_LAUNCHER}
    -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
    -DCMAKE_OSX_ARCHITECTURES=${OSX_ARCHITECTURES_LISTSEP}
    -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
)
include_directories(SYSTEM
  ${CMAKE_CURRENT_BINARY_DIR}/lib/libASPL/include
)
list(PREPEND CMAKE_PREFIX_PATH
  ${CMAKE_CURRENT_BINARY_DIR}/lib/libASPL/lib/cmake
)
